name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      dockerfile:
        description: 'which dockerfile to build'
        required: true
      tagname:
          description: 'tag name'
          required: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Validate dockerfile path
      id: dockerfile_dir
      run: |
        if [ ! -f "${{ github.workspace }}/${{ github.event.inputs.dockerfile }}" ]; then
          echo "Dockerfile not found at given path"
          exit 1
        fi
        context=$(dirname "${{ github.event.inputs.dockerfile }}")
        echo "::set-output name=context::$context"
        echo "::set-output name=image::${context//\//-}"

    - name: build torch image
      uses: docker/build-push-action@v2
      with:
        context: ${{ steps.dockerfile_dir.outputs.context }}
        file: ${{ github.event.inputs.dockerfile }}
        tags: |
          ghcr.io/${{ github.repository_owner }}/${{ steps.dockerfile_dir.outputs.image }}:${{ github.event.inputs.tagname }}
        push: true